<?php
header("Content-Type: application/json");
require_once("dbconfig.php"); // Expects constants: DB_HOST, DB_USER, DB_PASS, DB_NAME

// // 1. Receive JSON payload arriving from welcome.js
// $input = json_decode(file_get_contents("php://input"), true);

// $name          = trim($input["name"] ?? "");
// $goal          = trim($input["goal"] ?? "");
// $skillLevel    = trim($input["skillLevel"] ?? "");
// $studyTime     = intval($input["studyTime"] ?? 0);
// $learningStyle = trim($input["learningStyle"] ?? "");

// if (empty($name) || empty($goal)) {
//     echo json_encode(["success" => false, "message" => "Required profile criteria missing."]);
//     exit;
// }

// // 2. Establish standard connection using basic MySQLi
// $conn = mysqli_connect(DB_HOST, DB_USER, DB_PASS, DB_NAME);

// Check if the connection worked
if (!$conn) {
    echo json_encode([
        "success" => false, 
        "message" => "Database connection failure: " . mysqli_connect_error()
    ]);
    exit;
}

// 3. Sanitize inputs to protect against SQL Injection
$nameEscaped          = mysqli_real_escape_string($conn, $name);
$goalEscaped          = mysqli_real_escape_string($conn, $goal);
$skillLevelEscaped    = mysqli_real_escape_string($conn, $skillLevel);
$learningStyleEscaped = mysqli_real_escape_string($conn, $learningStyle);

// 4. Construct and run the query string
$sql = "INSERT INTO students (name, goal_title, skill_level, study_time_hours, learning_style, study_streak, progress_percentage, average_score, current_stage) 
        VALUES ('$nameEscaped', '$goalEscaped', '$skillLevelEscaped', $studyTime, '$learningStyleEscaped', 0, 0, 0, 'Getting Started Foundations')";

if (mysqli_query($conn, $sql)) {
    // 5. Grab the auto-increment primary key ID generated by MySQL
    $newStudentId = mysqli_insert_id($conn);
    
    echo json_encode([
        "success" => true,
        "student_id" => $newStudentId
    ]);
} else {
    echo json_encode([
        "success" => false,
        "message" => "SQL query error: " . mysqli_error($conn)
    ]);
}

// 6. Close connection link
mysqli_close($conn);
?>